"""initial

Revision ID: d983da3d54af
Revises: 
Create Date: 2025-10-11 21:26:24.015761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd983da3d54af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=500), nullable=False),
    sa.Column('full_name', sa.String(length=500), nullable=True),
    sa.Column('disabled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('password_hash', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('todo_tasks',
    sa.Column('title', sa.String(length=500), nullable=False, comment='Заголовок задачи'),
    sa.Column('description', sa.String(length=5000), nullable=False, comment='Описание задачи'),
    sa.Column('responsible_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['responsible_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo_tasks')
    op.drop_table('users')
    # ### end Alembic commands ###
